#! /bin/sh

# usage: sh package-updater.sh <path to fedora-scm> <path to new source>

BRANCHES="f17 f16 f15" # branches on which should be built
PACKAGER="Kalpa Welivitigoda <callkalpa@gmail.com>"

PACKAGE_PATH="$1"
SOURCE_PATH="$2"

# display error message and exit
error_exit(){
	echo "ERROR: $1"
	exit 1
}

# iterates through branches and build
go_through_branches(){
	for branch in $BRANCHES;
	do
		fedpkg switch-branch "$branch"
		git merge master
		git push
		fedpkg build &
		sleep 5
	done
}

# extract spec file name
get_spec_file_name(){
	SPEC_FILE="$(basename "$PACKAGE_PATH").spec"
}

# generate changelog
generate_changelog(){
	changelog_msg="* $(date "+%a %b %d %Y") $PACKAGER - $VERSION-1\n- $iCHANGELOG_MSG\n"
}

# display last changelog message
display_last_changelog(){
	echo "Last changelog:"
	grep -A3 %changelog $SPEC_FILE
}

# display the last commit, change spec file, commit and build for rawhide
change_spec_and_build(){

	generate_changelog
	tmp="$(mktemp)"
	sed -e '/^%changelog/ a\'"$changelog_msg"'' -e '/^Version/c\'"Version:\t$VERSION"''  "$SPEC_FILE" > "$tmp"
	mv "$tmp" "$SPEC_FILE"

	git commit -am "$GIT_COMMIT"
	git push
	fedpkg build &
	sleep 5
}

get_inputs(){
	echo -n "Enter Version-Release (ex: 21-1): "
	read VERSION
	if [ -z $VERSION ]
	then
		error_exit "Invalid version"
	fi

	echo -n "Enter changelog message: "
	read CHANGELOG_MSG
	if [ -z $CHANGELOG_MSG ]
	then
		error_exit "Invalid changelog message"
	fi

	echo -n "Enter git commit message: "
	read GIT_COMMIT
	if [ -z $GIT_COMMIT ]
	then
		error_exit "Invalid git commit message"
	fi
	
}

display_usage(){
	echo "usage: package-update <fedora-package path> <package source path>"
}

# validate arguments
if [ "$#" -eq "2" -a -e "$PACKAGE_PATH" -a -e "$SOURCE_PATH" ]
then
	cd "$PACKAGE_PATH"
	get_spec_file_name
	display_last_changelog
	get_inputs
	fedpkg switch-branch master
	fedpkg new-sources "$SOURCE_PATH"
	change_spec_and_build
	go_through_branches
else
	echo "Invalid arguments"
	display_usage
	exit 1
fi

fedpkg switch-branch master

exit 0
